app:
  port: 8000

db:
  driver: "mssql"
  host: "127.0.0.1"
  port: 1433
  username: sa
  password: 12345Cat
  database: banking

jwt:
  secretKey: "secretKey"

oAuth:
  google :
    clientID : ""
    clientSecret : ""
  line : 
    clientID : ""
    clientSecret : ""
